
package com.example.webservicedemo.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoService", targetNamespace = "http://service.webservicedemo.example.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SayName")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SayName", targetNamespace = "http://service.webservicedemo.example.com", className = "com.example.webservicedemo.service.SayName")
    @ResponseWrapper(localName = "SayNameResponse", targetNamespace = "http://service.webservicedemo.example.com", className = "com.example.webservicedemo.service.SayNameResponse")
    public String sayName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
